---
language: bash
os:
  - linux
  - osx

addons:
  apt:
    sources:
      - sourceline: 'ppa:duggan/bats'
        packages:
          - libcurl4-openssl-dev
          - libelf-dev
          - libdw-dev
          - cmake
          - git-core
          - bats
          - yamllint

before_install:
  - "if [ $TRAVIS_OS_NAME = osx ]; then
        brew update && brew upgrade git && brew install bats shellcheck;
    fi"

script:
  - bats ./tests/acceptance/
  - shellcheck -x bashlight
  - shellcheck -x *.bash
  - shellcheck -x **/*.bash
  - yamllint .

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-master &&
  mkdir -p coverage &&
  kcov coverage bashlight &&
  bash <(curl -s https://codecov.io/bash)
