---
platform: linux
image_resource:
  type: docker-image
  source: {repository: vergissberlin/alpine-development}

inputs:
- name: resource-bashlight

outputs:
- name: test-result

run:
  path: sh
  args: ['./resource-bashlight/ci/scripts/run.sh']
